server:
  port: 8880

test:
  hello: HelloWorld1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: wiki
    url: jdbc:mysql://wiki@localhost/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: wiki