server:
  port: 8880

test:
  hello: HelloWorld1

#Data Source Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: wiki
    url: jdbc:mysql://wiki@localhost/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: wiki

# Redis Config
  redis:
    host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
    password: Redis000
    port: 6379

#Mybatis scan all mapper.xml
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# 打印所有的sql日志：sql, 参数, 结果
logging:
  level:
    com:
      wikibase:
        mapper: trace

